/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package testproject;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author alika
 */
public class MenuWindowJFrame extends javax.swing.JFrame {
     private Connection connection;

    /**
     * Creates new form MenuWindowJFrame
     */
    public MenuWindowJFrame(Connection connection) {
    this.connection=connection;
        
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblMenu = new javax.swing.JLabel();
        btnUserManagementPanel = new javax.swing.JButton();
        btnPrisonerInformation = new javax.swing.JButton();
        btnStatistics = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblMenu.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblMenu.setText("WELCOME TO JAIL MANAGEMENT SYSTEM ");

        btnUserManagementPanel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnUserManagementPanel.setText("User Management Panel");
        btnUserManagementPanel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUserManagementPanelActionPerformed(evt);
            }
        });

        btnPrisonerInformation.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnPrisonerInformation.setText("Prisoner Informations");
        btnPrisonerInformation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrisonerInformationActionPerformed(evt);
            }
        });

        btnStatistics.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnStatistics.setText("Get Prison Statistics");
        btnStatistics.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStatisticsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(113, 113, 113)
                        .addComponent(btnUserManagementPanel))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(123, 123, 123)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnStatistics)
                            .addComponent(btnPrisonerInformation))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 29, Short.MAX_VALUE)
                .addComponent(lblMenu)
                .addGap(32, 32, 32))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(lblMenu)
                .addGap(18, 18, 18)
                .addComponent(btnUserManagementPanel)
                .addGap(18, 18, 18)
                .addComponent(btnStatistics)
                .addGap(18, 18, 18)
                .addComponent(btnPrisonerInformation)
                .addContainerGap(57, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnUserManagementPanelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUserManagementPanelActionPerformed
        // TODO add your handling code here:
            PeopleWindowJFrame framePeople = new PeopleWindowJFrame(connection);
            dispose();
            framePeople.setVisible(true);
            
    }//GEN-LAST:event_btnUserManagementPanelActionPerformed

    private void btnPrisonerInformationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrisonerInformationActionPerformed
        // TODO add your handling code here:
        PrisonerInformationJFrame framePrisoners = new PrisonerInformationJFrame(connection);
        dispose();
        framePrisoners.setVisible(true);
    }//GEN-LAST:event_btnPrisonerInformationActionPerformed

    private void btnStatisticsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStatisticsActionPerformed
        // TODO add your handling code here:
        StatisticsWindowJFrame frameStatistics = new StatisticsWindowJFrame(connection);
        dispose();
        frameStatistics.setVisible(true);
    }//GEN-LAST:event_btnStatisticsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuWindowJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuWindowJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuWindowJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuWindowJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPrisonerInformation;
    private javax.swing.JButton btnStatistics;
    private javax.swing.JButton btnUserManagementPanel;
    private javax.swing.JLabel lblMenu;
    // End of variables declaration//GEN-END:variables
}
