/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package testproject;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author alika
 */
public class StatisticsWindowJFrame extends javax.swing.JFrame {
     private Connection connection;

    /**
     * Creates new form StatisticsWindowJFrame
     */
     private double resultCellCapacity;
     private double resultNumberOfPrisoner;
     
    public StatisticsWindowJFrame(Connection connection){
                this.connection=connection;
                initComponents();
                
        
        try {
            String sql="Select count(*) from people;";
            PreparedStatement pst = connection.prepareStatement(sql);
            ResultSet rs = pst.executeQuery();
            rs.next();
            String str=rs.getString("count(*)");
            txtNumbOfPeople.setText(str);      
        } catch (SQLException ex) {
            System.out.println(ex.toString());
        }
        
        try {
            String sql="Select count(*) from staff;";
            PreparedStatement pst = connection.prepareStatement(sql);
            ResultSet rs = pst.executeQuery();
            rs.next();
            String str=rs.getString("count(*)");
            txtNumbStaff.setText(str);      
        } catch (SQLException ex) {
            System.out.println(ex.toString());
        }
        try {
            String sql="Select count(*) from prisoners;";
            PreparedStatement pst = connection.prepareStatement(sql);
            ResultSet rs = pst.executeQuery();
            rs.next();
            String str=rs.getString("count(*)");
            txtNumbPrisoner.setText(str);      
        } catch (SQLException ex) {
            System.out.println(ex.toString());
        }
        try {
            String sql="Select count(*) from guards;";
            PreparedStatement pst = connection.prepareStatement(sql);
            ResultSet rs = pst.executeQuery();
            rs.next();
            String str=rs.getString("count(*)");
            txtNumbGuards.setText(str);      
        } catch (SQLException ex) {
            System.out.println(ex.toString());
        }
        try {
            String sql="select sum(cellCapacity) from cells;";
            PreparedStatement pst = connection.prepareStatement(sql);
            ResultSet rs = pst.executeQuery();
            rs.next();
            String str=rs.getString("sum(cellCapacity)");
            txtCellCapacity.setText(str);      
        } catch (SQLException ex) {
            System.out.println(ex.toString());
        }
      
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane6 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        lblNumbofStaff = new javax.swing.JLabel();
        lblPrisoner = new javax.swing.JLabel();
        lblCellCapacity = new javax.swing.JLabel();
        lblGuards = new javax.swing.JLabel();
        lblNumbOfPeople = new javax.swing.JLabel();
        txtNumbOfPeople = new javax.swing.JTextField();
        txtNumbStaff = new javax.swing.JTextField();
        txtCellCapacity = new javax.swing.JTextField();
        txtNumbPrisoner = new javax.swing.JTextField();
        txtNumbGuards = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane6.setViewportView(jList1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblNumbofStaff.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblNumbofStaff.setText("Number of staff :");
        getContentPane().add(lblNumbofStaff, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 290, -1, -1));

        lblPrisoner.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblPrisoner.setText("Number of prisoner :");
        getContentPane().add(lblPrisoner, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 310, -1, 30));

        lblCellCapacity.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblCellCapacity.setText("Cell capacity : ");
        getContentPane().add(lblCellCapacity, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 220, -1, -1));

        lblGuards.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblGuards.setText("Number of guards :");
        getContentPane().add(lblGuards, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 340, -1, -1));

        lblNumbOfPeople.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblNumbOfPeople.setText("Number of people :");
        getContentPane().add(lblNumbOfPeople, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 250, -1, -1));

        txtNumbOfPeople.setEditable(false);
        txtNumbOfPeople.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtNumbOfPeople.setText("jTextField1");
        getContentPane().add(txtNumbOfPeople, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 250, -1, -1));

        txtNumbStaff.setEditable(false);
        txtNumbStaff.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtNumbStaff.setText("jTextField1");
        getContentPane().add(txtNumbStaff, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 280, -1, -1));

        txtCellCapacity.setEditable(false);
        txtCellCapacity.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtCellCapacity.setText("jTextField1");
        txtCellCapacity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCellCapacityActionPerformed(evt);
            }
        });
        getContentPane().add(txtCellCapacity, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 220, -1, -1));

        txtNumbPrisoner.setEditable(false);
        txtNumbPrisoner.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtNumbPrisoner.setText("jTextField1");
        getContentPane().add(txtNumbPrisoner, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 310, 91, -1));

        txtNumbGuards.setEditable(false);
        txtNumbGuards.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtNumbGuards.setText("jTextField1");
        txtNumbGuards.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNumbGuardsActionPerformed(evt);
            }
        });
        getContentPane().add(txtNumbGuards, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 340, -1, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("STATISTICS OF JAIL");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 160, -1, 58));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/testproject/prisonfoto.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 20, -1, 141));

        btnBack.setText("BACK");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        getContentPane().add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, 40));
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 370, 40, 50));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNumbGuardsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNumbGuardsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNumbGuardsActionPerformed

    private void txtCellCapacityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCellCapacityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCellCapacityActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        // TODO add your handling code here:
        dispose();
        MenuWindowJFrame Menuframe = new MenuWindowJFrame(connection);
        Menuframe.setVisible(true);
        

    }//GEN-LAST:event_btnBackActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StatisticsWindowJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StatisticsWindowJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StatisticsWindowJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StatisticsWindowJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        //java.awt.EventQueue.invokeLater(new Runnable() {
           // public void run() {
                
                
                
               // new StatisticsWindowJFrame(connection).setVisible(true);
            }
       // });
    //}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JList<String> jList1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JLabel lblCellCapacity;
    private javax.swing.JLabel lblGuards;
    private javax.swing.JLabel lblNumbOfPeople;
    private javax.swing.JLabel lblNumbofStaff;
    private javax.swing.JLabel lblPrisoner;
    private javax.swing.JTextField txtCellCapacity;
    private javax.swing.JTextField txtNumbGuards;
    private javax.swing.JTextField txtNumbOfPeople;
    private javax.swing.JTextField txtNumbPrisoner;
    private javax.swing.JTextField txtNumbStaff;
    // End of variables declaration//GEN-END:variables
}
