-- MySQL Script generated by MySQL Workbench
-- Thu Dec  1 23:38:15 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema JailManagementSystem
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `JailManagementSystem` ;

-- -----------------------------------------------------
-- Schema JailManagementSystem
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `JailManagementSystem` DEFAULT CHARACTER SET utf8 ;
USE `JailManagementSystem` ;

-- -----------------------------------------------------
-- Table `JailManagementSystem`.`People`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `JailManagementSystem`.`People` ;

CREATE TABLE IF NOT EXISTS `JailManagementSystem`.`People` (
  `peopleID` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(45) NOT NULL,
  `Surname` VARCHAR(45) NOT NULL,
  `BirthDate` DATE NOT NULL,
  `Adress` TEXT NOT NULL,
  `Gender` VARCHAR(45) NULL,
  `phoneNumber` VARCHAR(11) NOT NULL,
  PRIMARY KEY (`peopleID`),
  UNIQUE INDEX `peopleID_UNIQUE` (`peopleID` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `JailManagementSystem`.`StaffPositions`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `JailManagementSystem`.`StaffPositions` ;

CREATE TABLE IF NOT EXISTS `JailManagementSystem`.`StaffPositions` (
  `positionID` INT NOT NULL AUTO_INCREMENT,
  `Salary` DOUBLE NOT NULL,
  `JobTitle` VARCHAR(45) NOT NULL,
  `DutyExplanation` TEXT NOT NULL,
  PRIMARY KEY (`positionID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `JailManagementSystem`.`Staff`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `JailManagementSystem`.`Staff` ;

CREATE TABLE IF NOT EXISTS `JailManagementSystem`.`Staff` (
  `People_peopleID` INT NOT NULL,
  `dateStarted` DATE NOT NULL,
  `dateQuit` DATE NULL,
  `WorkingLength` YEAR NULL,
  `StaffPositions_positionID` INT NOT NULL,
  PRIMARY KEY (`People_peopleID`),
  INDEX `fk_Staff_Staff Positions1_idx` (`StaffPositions_positionID` ASC) VISIBLE,
  CONSTRAINT `fk_Prisoners_People`
    FOREIGN KEY (`People_peopleID`)
    REFERENCES `JailManagementSystem`.`People` (`peopleID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Staff_Staff Positions1`
    FOREIGN KEY (`StaffPositions_positionID`)
    REFERENCES `JailManagementSystem`.`StaffPositions` (`positionID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `JailManagementSystem`.`Visitors`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `JailManagementSystem`.`Visitors` ;

CREATE TABLE IF NOT EXISTS `JailManagementSystem`.`Visitors` (
  `NumberOfVisit` INT NULL DEFAULT 0,
  `People_peopleID` INT NOT NULL,
  INDEX `fk_Visitors_People1_idx` (`People_peopleID` ASC) VISIBLE,
  PRIMARY KEY (`People_peopleID`),
  CONSTRAINT `fk_Visitors_People1`
    FOREIGN KEY (`People_peopleID`)
    REFERENCES `JailManagementSystem`.`People` (`peopleID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `JailManagementSystem`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `JailManagementSystem`.`user` ;

CREATE TABLE IF NOT EXISTS `JailManagementSystem`.`user` (
  `username` VARCHAR(16) NOT NULL,
  `email` VARCHAR(255) NULL,
  `password` VARCHAR(32) NOT NULL,
  `create_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP);


-- -----------------------------------------------------
-- Table `JailManagementSystem`.`category`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `JailManagementSystem`.`category` ;

CREATE TABLE IF NOT EXISTS `JailManagementSystem`.`category` (
  `category_id` INT NOT NULL,
  `name` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`category_id`));


-- -----------------------------------------------------
-- Table `JailManagementSystem`.`timestamps`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `JailManagementSystem`.`timestamps` ;

CREATE TABLE IF NOT EXISTS `JailManagementSystem`.`timestamps` (
  `create_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `update_time` TIMESTAMP NULL);


-- -----------------------------------------------------
-- Table `JailManagementSystem`.`Visits`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `JailManagementSystem`.`Visits` ;

CREATE TABLE IF NOT EXISTS `JailManagementSystem`.`Visits` (
  `visitID` INT NOT NULL AUTO_INCREMENT,
  `visitDate` DATE NOT NULL,
  `ReasonOfVisit` TEXT NOT NULL,
  `Visitors_People_peopleID` INT NOT NULL,
  PRIMARY KEY (`visitID`),
  INDEX `fk_Visits_Visitors1_idx` (`Visitors_People_peopleID` ASC) VISIBLE,
  CONSTRAINT `fk_Visits_Visitors1`
    FOREIGN KEY (`Visitors_People_peopleID`)
    REFERENCES `JailManagementSystem`.`Visitors` (`People_peopleID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `JailManagementSystem`.`Cells`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `JailManagementSystem`.`Cells` ;

CREATE TABLE IF NOT EXISTS `JailManagementSystem`.`Cells` (
  `cellID` INT NOT NULL AUTO_INCREMENT,
  `cellName` VARCHAR(45) NOT NULL,
  `cellCapacity` INT NOT NULL,
  PRIMARY KEY (`cellID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `JailManagementSystem`.`Prisoners`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `JailManagementSystem`.`Prisoners` ;

CREATE TABLE IF NOT EXISTS `JailManagementSystem`.`Prisoners` (
  `People_peopleID` INT NOT NULL,
  `Height` INT NOT NULL,
  `WEİGHT` DOUBLE NOT NULL,
  `Haircolor` VARCHAR(15) NOT NULL,
  `SpesificApperanceSpecifications` TEXT NOT NULL,
  `Cells_cellID` INT NOT NULL,
  PRIMARY KEY (`People_peopleID`),
  INDEX `fk_Prisoners_Cells1_idx` (`Cells_cellID` ASC) VISIBLE,
  CONSTRAINT `fk_Prisoners_People1`
    FOREIGN KEY (`People_peopleID`)
    REFERENCES `JailManagementSystem`.`People` (`peopleID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Prisoners_Cells1`
    FOREIGN KEY (`Cells_cellID`)
    REFERENCES `JailManagementSystem`.`Cells` (`cellID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `JailManagementSystem`.`OldPrisoners`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `JailManagementSystem`.`OldPrisoners` ;

CREATE TABLE IF NOT EXISTS `JailManagementSystem`.`OldPrisoners` (
  `Prisoners_People_peopleID` INT NOT NULL,
  `releaseDate` DATE NOT NULL,
  `ReasonOfRelease` TEXT NOT NULL,
  PRIMARY KEY (`Prisoners_People_peopleID`),
  CONSTRAINT `fk_OldPrisoners(mapustan kurtulmus)_Prisoners1`
    FOREIGN KEY (`Prisoners_People_peopleID`)
    REFERENCES `JailManagementSystem`.`Prisoners` (`People_peopleID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `JailManagementSystem`.`CriminalCases`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `JailManagementSystem`.`CriminalCases` ;

CREATE TABLE IF NOT EXISTS `JailManagementSystem`.`CriminalCases` (
  `caseID` INT NOT NULL AUTO_INCREMENT,
  `reasonOfCase` TEXT NOT NULL,
  `DangerLevel` INT NULL,
  `punishmentStartDate` DATE NOT NULL,
  `punishmentEndDate` DATE NULL,
  `Prisoners_People_peopleID` INT NOT NULL,
  PRIMARY KEY (`caseID`),
  INDEX `fk_CriminalCases_Prisoners1_idx` (`Prisoners_People_peopleID` ASC) VISIBLE,
  CONSTRAINT `fk_CriminalCases_Prisoners1`
    FOREIGN KEY (`Prisoners_People_peopleID`)
    REFERENCES `JailManagementSystem`.`Prisoners` (`People_peopleID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `JailManagementSystem`.`PrisonerProblems`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `JailManagementSystem`.`PrisonerProblems` ;

CREATE TABLE IF NOT EXISTS `JailManagementSystem`.`PrisonerProblems` (
  `problemID` INT NOT NULL AUTO_INCREMENT,
  `issueDescription` TEXT NOT NULL,
  `dangerLevel` INT NOT NULL,
  PRIMARY KEY (`problemID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `JailManagementSystem`.`Guards`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `JailManagementSystem`.`Guards` ;

CREATE TABLE IF NOT EXISTS `JailManagementSystem`.`Guards` (
  `People_peopleID` INT NOT NULL,
  `Salary` DOUBLE NOT NULL,
  `Height` DOUBLE NOT NULL,
  `Weight` DOUBLE NOT NULL,
  PRIMARY KEY (`People_peopleID`),
  CONSTRAINT `fk_Guards_People1`
    FOREIGN KEY (`People_peopleID`)
    REFERENCES `JailManagementSystem`.`People` (`peopleID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `JailManagementSystem`.`PrisonerPositions`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `JailManagementSystem`.`PrisonerPositions` ;

CREATE TABLE IF NOT EXISTS `JailManagementSystem`.`PrisonerPositions` (
  `prisonerPositionID` INT NOT NULL AUTO_INCREMENT,
  `JobTitle` VARCHAR(45) NOT NULL,
  `DutyExplanation` TEXT NOT NULL,
  `hourlyFee` DOUBLE NULL DEFAULT 0,
  PRIMARY KEY (`prisonerPositionID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `JailManagementSystem`.`PrisonerStaff`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `JailManagementSystem`.`PrisonerStaff` ;

CREATE TABLE IF NOT EXISTS `JailManagementSystem`.`PrisonerStaff` (
  `Prisoners_People_peopleID` INT NOT NULL,
  `WorkingReason` TEXT NOT NULL,
  `StartWorkDate` DATE NOT NULL,
  `QuitWorkDate` DATE NULL,
  `PrisonerPositions_prisonerPositionID` INT NOT NULL,
  PRIMARY KEY (`Prisoners_People_peopleID`),
  INDEX `fk_Prisoner Staff_Prisoner Positions1_idx` (`PrisonerPositions_prisonerPositionID` ASC) VISIBLE,
  CONSTRAINT `fk_Prisoner Staff_Prisoners1`
    FOREIGN KEY (`Prisoners_People_peopleID`)
    REFERENCES `JailManagementSystem`.`Prisoners` (`People_peopleID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Prisoner Staff_Prisoner Positions1`
    FOREIGN KEY (`PrisonerPositions_prisonerPositionID`)
    REFERENCES `JailManagementSystem`.`PrisonerPositions` (`prisonerPositionID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `JailManagementSystem`.`PrisonerProblems_has_Prisoners`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `JailManagementSystem`.`PrisonerProblems_has_Prisoners` ;

CREATE TABLE IF NOT EXISTS `JailManagementSystem`.`PrisonerProblems_has_Prisoners` (
  `PrisonerProblems_problemID` INT NOT NULL,
  `Prisoners_People_peopleID` INT NOT NULL,
  PRIMARY KEY (`PrisonerProblems_problemID`, `Prisoners_People_peopleID`),
  INDEX `fk_PrisonerProblems_has_Prisoners_Prisoners1_idx` (`Prisoners_People_peopleID` ASC) VISIBLE,
  INDEX `fk_PrisonerProblems_has_Prisoners_PrisonerProblems1_idx` (`PrisonerProblems_problemID` ASC) VISIBLE,
  CONSTRAINT `fk_PrisonerProblems_has_Prisoners_PrisonerProblems1`
    FOREIGN KEY (`PrisonerProblems_problemID`)
    REFERENCES `JailManagementSystem`.`PrisonerProblems` (`problemID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_PrisonerProblems_has_Prisoners_Prisoners1`
    FOREIGN KEY (`Prisoners_People_peopleID`)
    REFERENCES `JailManagementSystem`.`Prisoners` (`People_peopleID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
